/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as JoinCodeRouteImport } from './routes/join/$code'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as TeamsTeamIdSettingsRouteImport } from './routes/teams/$teamId/settings'
import { Route as TeamsTeamIdScheduleRouteImport } from './routes/teams/$teamId/schedule'
import { Route as TeamsTeamIdRosterRouteImport } from './routes/teams/$teamId/roster'
import { Route as TeamsTeamIdPaymentsRouteImport } from './routes/teams/$teamId/payments'
import { Route as TeamsTeamIdAnnouncementsRouteImport } from './routes/teams/$teamId/announcements'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdSettingsRoute = TeamsTeamIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdScheduleRoute = TeamsTeamIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdRosterRoute = TeamsTeamIdRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdPaymentsRoute = TeamsTeamIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)
const TeamsTeamIdAnnouncementsRoute =
  TeamsTeamIdAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => TeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/announcements': typeof TeamsTeamIdAnnouncementsRoute
  '/teams/$teamId/payments': typeof TeamsTeamIdPaymentsRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/schedule': typeof TeamsTeamIdScheduleRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams': typeof TeamsIndexRoute
  '/teams/$teamId/announcements': typeof TeamsTeamIdAnnouncementsRoute
  '/teams/$teamId/payments': typeof TeamsTeamIdPaymentsRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/schedule': typeof TeamsTeamIdScheduleRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$code': typeof JoinCodeRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/teams/': typeof TeamsIndexRoute
  '/teams/$teamId/announcements': typeof TeamsTeamIdAnnouncementsRoute
  '/teams/$teamId/payments': typeof TeamsTeamIdPaymentsRoute
  '/teams/$teamId/roster': typeof TeamsTeamIdRosterRoute
  '/teams/$teamId/schedule': typeof TeamsTeamIdScheduleRoute
  '/teams/$teamId/settings': typeof TeamsTeamIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$token'
    | '/join/$code'
    | '/teams/$teamId'
    | '/teams/'
    | '/teams/$teamId/announcements'
    | '/teams/$teamId/payments'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/schedule'
    | '/teams/$teamId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$token'
    | '/join/$code'
    | '/teams/$teamId'
    | '/teams'
    | '/teams/$teamId/announcements'
    | '/teams/$teamId/payments'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/schedule'
    | '/teams/$teamId/settings'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/invite/$token'
    | '/join/$code'
    | '/teams/$teamId'
    | '/teams/'
    | '/teams/$teamId/announcements'
    | '/teams/$teamId/payments'
    | '/teams/$teamId/roster'
    | '/teams/$teamId/schedule'
    | '/teams/$teamId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinCodeRoute: typeof JoinCodeRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId/settings': {
      id: '/teams/$teamId/settings'
      path: '/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof TeamsTeamIdSettingsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/schedule': {
      id: '/teams/$teamId/schedule'
      path: '/schedule'
      fullPath: '/teams/$teamId/schedule'
      preLoaderRoute: typeof TeamsTeamIdScheduleRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/roster': {
      id: '/teams/$teamId/roster'
      path: '/roster'
      fullPath: '/teams/$teamId/roster'
      preLoaderRoute: typeof TeamsTeamIdRosterRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/payments': {
      id: '/teams/$teamId/payments'
      path: '/payments'
      fullPath: '/teams/$teamId/payments'
      preLoaderRoute: typeof TeamsTeamIdPaymentsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
    '/teams/$teamId/announcements': {
      id: '/teams/$teamId/announcements'
      path: '/announcements'
      fullPath: '/teams/$teamId/announcements'
      preLoaderRoute: typeof TeamsTeamIdAnnouncementsRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
  }
}

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdAnnouncementsRoute: typeof TeamsTeamIdAnnouncementsRoute
  TeamsTeamIdPaymentsRoute: typeof TeamsTeamIdPaymentsRoute
  TeamsTeamIdRosterRoute: typeof TeamsTeamIdRosterRoute
  TeamsTeamIdScheduleRoute: typeof TeamsTeamIdScheduleRoute
  TeamsTeamIdSettingsRoute: typeof TeamsTeamIdSettingsRoute
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdAnnouncementsRoute: TeamsTeamIdAnnouncementsRoute,
  TeamsTeamIdPaymentsRoute: TeamsTeamIdPaymentsRoute,
  TeamsTeamIdRosterRoute: TeamsTeamIdRosterRoute,
  TeamsTeamIdScheduleRoute: TeamsTeamIdScheduleRoute,
  TeamsTeamIdSettingsRoute: TeamsTeamIdSettingsRoute,
}

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinCodeRoute: JoinCodeRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
